SmartOrderRouterService:

  Name:
    settings-key: SmartOrderRouterService-Name

  Db:
    DataConnectionString:
      settings-key: SmartOrderRouterService-DataConnectionString
      types:
        - AzureTableStorage

    LogsConnectionString:
      settings-key: SmartOrderRouterService-LogsConnectionString
      types:
        - AzureTableStorage
  Rabbit:
    Subscribers:
      OrderBooks:
        ConnectionString:
          settings-key: RawPriceRabbitMq
          types:
            - RabbitMq
        Exchanges:
          settings-key: SmartOrderRouterService-Rabbit-Subscribers-OrderBooks-Exchanges
          types:
            - JsonArray
        QueueSuffix:
          settings-key: SmartOrderRouterService-Rabbit-Subscribers-OrderBooks-QueueSuffix
          
      Quotes:
        ConnectionString:
          settings-key: RawPriceRabbitMq
          types:
            - RabbitMq
        Exchanges:
          settings-key: SmartOrderRouterService-Rabbit-Subscribers-Quotes-Exchanges
          types:
            - JsonArray
        QueueSuffix:
          settings-key: SmartOrderRouterService-Rabbit-Subscribers-Quotes-QueueSuffix
          
  ExchangeAdapters:
    settings-key: SmartOrderRouterService-ExchangeAdapters
    types:
      - JsonArray

MarketInstrumentsServiceClient:
  ServiceUrl:
    settings-key: MarketInstrumentsServiceUrl

SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
        - AzureTableStorage
    QueueName:
      settings-key: SlackQueueName

MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl